
# Error codes
EC_INVALID_USERNAME   = 1
EC_USERNAME_EXISTS    = 2
EC_INVALID_PASSWORD   = 3
EC_PASSWORDS_MISMATCH = 4
EC_INVALID_EMAIL      = 5
EC_INVALID_CREDS      = 6
EC_ACCOUNT_DISABLED   = 7
EC_NOT_LOGGED_IN      = 8
EC_EMPTY_MESSAGE      = 9


